# Generated by Django 2.0.6 on 2018-08-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180802_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='schema_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
