# Generated by Django 2.0.6 on 2018-07-25 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180725_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rbn',
        ),
    ]
