# Generated by Django 2.0.6 on 2018-08-02 19:17

from django.db import migrations, models
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180802_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='schema_name',
            field=models.CharField(max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name]),
        ),
    ]
