# Generated by Django 2.0.6 on 2018-08-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180802_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='schema_name',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
