# Generated by Django 2.0.6 on 2018-07-26 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180707_1724'),
        ('accounts', '0004_user_retailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
