# Generated by Django 2.0.6 on 2018-07-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180728_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer',
            field=models.BooleanField(default=False),
        ),
    ]
