# Generated by Django 2.0.6 on 2018-07-30 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_user'),
        ('accounts', '0008_remove_user_user_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
